### ISSUE TITLE
可以增加一个使用账号密码登录吗

### ISSUE THREAD

**Issue by Mrkk1** [aifuxi/fuxiaochen#16]
如果可以，建议增加一个账号密码登录，避免与第三方强耦合。

**Comment by aifuxi** [comment]
使用账号密码登录容易被暴力破解，暂不考虑做这个功能，你可以自己实现，可以参考下面几篇文章

- [基于Next14+Auth5实现Github、Google、Gitee平台授权登录和邮箱密码登录](https://juejin.cn/post/7329736763060518931)

- [Implementing Credentials Provider on NextJS and NextAuth (Registration and Login)](https://blog.devso.io/implementing-credentials-provider-on-nextjs-and-nextauth)

- [NextJS Authentication with NextAuth, Prisma and Postgres.](https://medium.com/@rabin.nyaundi254/nextjs-authentication-with-nextauth-prisma-an-postgres-7d55b14e68ad)
