### ISSUE TITLE
项目很棒，但是我不知道该怎么部署到我的服务器上

### ISSUE THREAD

**Issue by Mrkk1** [aifuxi/fuxiaochen#17]
如果可以的话，可以编写一下readme，给出详细的服务器部署教程吗。感谢

**Comment by aifuxi** [comment]
- 部署视频：[手摸手教你如何部署fuxiaochen博客网站](https://www.bilibili.com/video/BV1vz421f7Jr/?share_source=copy_web&vd_source=8b381d6ef205d4d72391e78af40279c0)
- 部署文档：[手摸手教你如何部署fuxiaochen博客网站](https://fuxiaochen.com/blog/hand-to-hand-teaching-you-how-to-deploy-fuxiaochen-blog-site)
