### ISSUE TITLE
export const ERROR_NO_PERMISSION = new Error('无权限');

### ISSUE THREAD

**Issue by chenrongjian** [aifuxi/fuxiaochen#19]
登录后台创建标签的时候，提示export const ERROR_NO_PERMISSION = new Error('无权限');

**Comment by aifuxi** [comment]
如果你是自己部署或者在本地开发需要配置 .env.production 或者 .env.development，设置 NEXT_PUBLIC_ADMIN_EMAILS 字段包含你Github的邮箱，参考项目中 .env.example 末尾的示例
