### ISSUE TITLE
我的域名是 www.com,github中的 Authorization callback URL我应该填写什么，

### ISSUE THREAD

**Issue by chenrongjian** [aifuxi/fuxiaochen#20]
我的域名是 www.com,github中的 Authorization callback URL我应该填写什么，我填了http://www.com/admin不行，不是很理解，非常感谢老师能够解答下的

**Comment by aifuxi** [comment]
我举个2例子：http://localhost:6121/api/auth/callback/github 和
https://fuxiaochen.com/api/auth/callback/github
