### ISSUE TITLE
请如何在windows 环境下 使用make 命令

### ISSUE THREAD

**Issue by Laifang** [aifuxi/fuxiaochen#25]
如题 ，我主要是在windows 开发， 然后在linux 环境部署上线，请问要如何使用 项目中定义的make文件来提高效率

**Comment by aifuxi** [comment]
可以参考我的这篇文章，[解决 Go 中使用 Sqlite 报错 go-sqlite3 requires cgo to work](https://fuxiaochen.com/blog/fix-sqlite-requires-cgo)，安装  `MinGW` (C 和 C++ 的一个开发环境包)，配置好环境变量，就有 `make` 命令了
<img width="524" alt="image" src="https://github.com/aifuxi/fuxiaochen/assets/65325004/d890a939-f881-4232-a4f8-aafbadbc9a1a">
