### ISSUE TITLE
服务器部署项目一启动，硬盘读飙升 500以上Count/s，导致服务器崩溃

### ISSUE THREAD

**Issue by Stars-Chan** [aifuxi/fuxiaochen#35]
阿里云2核2G的轻量服务器，每次pnpm dev跑起来一会就崩掉，pnpm build的话会一直卡着，直至服务器崩溃，是因为项目对内存要求比较高吗

**Comment by Stars-Chan** [comment]
<img width="865" alt="image" src="https://github.com/user-attachments/assets/9cf18f57-ce5f-4177-bbbc-ba609ed4034d">

**Comment by aifuxi** [comment]
> 阿里云2核2G的轻量服务器，每次pnpm dev跑起来一会就崩掉，pnpm build的话会一直卡着，直至服务器崩溃，是因为项目对内存要求比较高吗

dev环境启动项目还是非常好资源的，不建议在服务器上跑dev；build时的那一下2核2G可能够呛，我看看后续能不能优化一下

**Comment by Lrunlin** [comment]
> > 阿里云2核2G的轻量服务器，每次pnpm dev跑起来一会就崩掉，pnpm build的话会一直卡着，直至服务器崩溃，是因为项目对内存要求比较高吗
> 
> dev环境启动项目还是非常耗资源的，不建议在服务器上跑dev；build时的那一下2核2G可能够呛，我看看后续能不能优化一下

改成  output: process.env.output ? "standalone" : undefined, 可以直接上传成果物

**Comment by Lrunlin** [comment]
> > 阿里云2核2G的轻量服务器，每次pnpm dev跑起来一会就崩掉，pnpm build的话会一直卡着，直至服务器崩溃，是因为项目对内存要求比较高吗
> 
> dev环境启动项目还是非常耗资源的，不建议在服务器上跑dev；build时的那一下2核2G可能够呛，我看看后续能不能优化一下

像我项目里面client启动和打包这样就能节约不少服务器资源 https://github.com/Lrunlin/blog
