### ISSUE TITLE
为什么要去除redis呢？

### ISSUE THREAD

**Issue by white0dew** [aifuxi/fuxiaochen#42]
你好，请问为什么要去除redis呢？我看到你最新的代码分支，试图把redis相关的代码给去掉

**Comment by aifuxi** [comment]
感觉redis这块我用的还是不太好，就想着先去掉，做的简单点。还有就是最近发现一个新的网站统计工具-[Umami](https://umami.is/docs)，感觉挺不错的想用它来代替

**Comment by white0dew** [comment]
> 感觉redis这块我用的还是不太好，就想着先去掉，做的简单点。还有就是最近发现一个新的网站统计工具-[Umami](https://umami.is/docs)，感觉挺不错的想用它来代替

自建redis有个好处就是可以自定义，比如筛选出最热的页面等

**Comment by white0dew** [comment]
> 感觉redis这块我用的还是不太好，就想着先去掉，做的简单点。还有就是最近发现一个新的网站统计工具-[Umami](https://umami.is/docs)，感觉挺不错的想用它来代替

hi，umami我看过了，确实很不错，打算在自己的网站上试试：https://offernow.cn

**Comment by white0dew** [comment]
@aifuxi xiaochen，我最近有个疑惑，什么时候使用api什么时候使用server action呢？

**Comment by aifuxi** [comment]
现在server action应该能替代大部分api的功能了吧
