### ISSUE TITLE
错误无法透出：An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

### ISSUE THREAD

**Issue by white0dew** [aifuxi/fuxiaochen#47]
怎么解决这个问题呢？An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

**Comment by aifuxi** [comment]
出现这个错误是因为我在server action中的接口里面有throw Error的操作，如果要避免出现这个问题的话就把throw Error的部分都删除掉应该就可以了，线上环境会报这个错，本地开发环境没问题

**Comment by white0dew** [comment]
> 出现这个错误是因为我在server action中的接口里面有throw Error的操作，如果要避免出现这个问题的话就把throw Error的部分都删除掉应该就可以了，线上环境会报这个错，本地开发环境没问题

最后我把serveraction的err报了一层，在上游来判断是不是错误

**Comment by Carl0608** [comment]
> throw Error

是在判断是否有权限这里么？noPermission 这个方法里
