### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by AsakaLan** [aifuxi/fuxiaochen#48]
按照Readme部署成功后，Login界面的umami username和password是什么呀，在哪个文件嘞，readme没看见啊

**Comment by aifuxi** [comment]
Umami安装后，刚开始的默认用户名和密码都是admin，可以看这个文档：https://umami.is/docs/login

**Comment by AsakaLan** [comment]
博主可以给个vx嘛，想具体请教一下，但是我是新手，可能会问的有点多，很喜欢你的博客风格



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月22日 16:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [aifuxi/fuxiaochen] 登录问题 (Issue #48) |

Umami安装后，刚开始的默认用户名和密码都是admin，可以看这个文档：https://umami.is/docs/login

**Comment by aifuxi** [comment]
> 博主可以给个vx嘛，想具体请教一下，但是我是新手，可能会问的有点多，很喜欢你的博客风格
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年11月22日 16:34 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>、State ***@***.***> | | 主题 | Re: [aifuxi/fuxiaochen] 登录问题 (Issue #48) | Umami安装后，刚开始的默认用户名和密码都是admin，可以看这个文档：https://umami.is/docs/login — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

已在B站私信回复你了
